# coding: utf-8

"""
    Insights Upload Service

    The Upload Service is designed to ingest payloads from customers and distribute them via a message queue to other Platform services.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sadams@redhat.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Insights Upload Service",
    author_email="sadams@redhat.com",
    url="",
    keywords=["Swagger", "Insights Upload Service"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    The Upload Service is designed to ingest payloads from customers and distribute them via a message queue to other Platform services.  # noqa: E501
    """
)
