# coding: utf-8

# flake8: noqa

"""
    Insights Upload Service

    The Upload Service is designed to ingest payloads from customers and distribute them via a message queue to other Platform services.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sadams@redhat.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.base_api import BaseApi
from swagger_client.api.status_api import StatusApi
from swagger_client.api.upload_api import UploadApi
from swagger_client.api.version_api import VersionApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
