# coding: utf-8

"""
    Insights Upload Service

    The Upload Service is designed to ingest payloads from customers and distribute them via a message queue to other Platform services.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sadams@redhat.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.base_api import BaseApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBaseApi(unittest.TestCase):
    """BaseApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.base_api.BaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_root_handler_get(self):
        """Test case for root_handler_get

        Checks if the application is running  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
