# coding: utf-8

# flake8: noqa
"""
    Insights Upload Service

    The Upload Service is designed to ingest payloads from customers and distribute them via a message queue to other Platform services.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sadams@redhat.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
